name: Deploy to Azure
# add on label only
on:
  push:
    branches:
      - azure-deploy
      - main
  pull_request:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: nuggets-personal-crm
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "14.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        env:
          CI: false
          DB_KEY: ${{ secrets.DB_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          npm install
          npm run client-install
          npm run build --if-present
          npm ci
          npx playwright install-deps
          npx playwright install
          npm start & npx wait-on http://127.0.0.1:8080
          npm run client & npx wait-on http://127.0.0.1:3000
          npm run e2e 
          npm run jest-install --if-present
          npm run test --if-present
          npm run uninstall-jest --if-present

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        env:
          CI: false
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}